### PR TITLE
Add variable SID expiration time

### PR DESCRIPTION
**Pull request by rubeecube**
Trying to fix an issue in Home Assistant - the Integration works for 20 mins then stops, then an hour after it works again - since the SID is renewed every hour - could be the cause?

### CODE REVIEW

**Comment by jafar-atili** [comment]
Hi @rubeecube,

Thank you for your contribution!

Do you think that the SID should be renewed every 20 minutes now? If yes, have you tested renewing every 20 minutes?

**Comment by rubeecube** [comment]
Hi @jafar-atili 

TL;DR, nothing urgent seems ok now

The issue seems now fixed on Electra side, not sure what happened

The pattern of the error timings (see below) made me to think we should change it to 19 mins, I guess it should be configurable , using the manual pyElectra I saw no issues + reloading the lib fixed it (Guessing setting the sid to None fixed the issue).

Or you could force a re_sid in case of errors

I now have a "Backup AC" in case there is an error (Using the other electrasmart integration)
I monitor the downtimes, and there was no majour issue in the last 48h

````text 
... Working from 0757 to 0816
... Working from 0857 to 0916
... Working from 0957 to 1016
... Working from 1057 to 1117
... Working from 1157 to 1217
... Working from 1257 to 1440
... Working from 1457 to 1535
... Working from 1557 to 1635

... Failing from 0817 to 0853
... Failing from 0917 to 0956
... Failing from 1017 to 1056
... Failing from 1117 to 1156
... Failing from 1217 to 1256
... Failing from 1441 to 1456
... Failing from 1534 to 1556
... Failing from 1634 to 1656```

**Comment by liorfranko** [comment]
@jafar-atili I'm still getting the same errors from the Home-Assitant integration.

**Comment by jafar-atili** [comment]
Please reach out in discord to discuss this

jafar_atili

**Comment by DavidConnack** [comment]
Im also getting this error,
Restarting Home Assistant resolves it temporarily for me (I assume it refreshes the SID).
It then fails again after a while.

**Comment by rubeecube** [comment]
Another way to solve: https://github.com/jafar-atili/pyElectra/pull/5 - explicit SID reset

**Comment by jafar-atili** [comment]
Fixed in https://github.com/jafar-atili/pyElectra/pull/6

**Pull request closed without merging**
